### ISSUE TITLE
As a user, it would be easier to have the facet field name written automatically when creating a new facet

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#165]
See @lilimelgar 's comment below

**Acceptance criteria**
- [ ] use the first word of the prettified field name as the label for the facet
- [ ] make sure this approach is sustainable for all collection (configs)

**Comment by lilimelgar** [comment]
This issue is solved, that is, when a user selects to add a new facet, the label is written automatically. One way to solve the long labels could be to just use as facet name the first part of the label, e.g.: 

![screen shot 2018-11-07 at 15 48 24](https://user-images.githubusercontent.com/8133228/48138427-99581280-e2a4-11e8-9146-bd62bd542abd.png)

Instead of copying the entire label, it could copy just "annotation".

@jblom Is this a good solution?

**Comment by jblom** [comment]
@lilimelgar I'd say yes, but it needs to be checked for every collection to be sure.

**Comment by lilimelgar** [comment]
@avlisodraude As we discussed, don't make any changes to the field name, but keep the three dots to shorten the field labels when the facet is created. What needs to be done is to apply the "three dot" solution to the facets that have no content:

![screen shot 2018-12-11 at 16 16 13](https://user-images.githubusercontent.com/8133228/49809795-1c66ff80-fd60-11e8-8b5d-507166cdd0cb.png)

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

Done as and tested preliminary with @lilimelgar .
@lilimelgar : Please check issue and comment/close. 

**Testing branch** (labo-components):
_task/#165-style-facet-headers_

**Comment by lilimelgar** [comment]
We checked this together, it works well.
