### ISSUE TITLE
As a user, I would like to be able to switch in the Comparative search tool between line chart and bar chart

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#166]
@lilimelgar commented on [Sun Nov 19 2017](https://github.com/CLARIAH/wp5_mediasuite/issues/192)

Add switch between graphic type in the comparative search.

**Comment by lilimelgar** [comment]
@avlisodraude This seems like an easy fix, please check it it could go in this sprint.

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

Issue done in labo-components project, branch _"task/#166-Add-histogram-to-comparative-tool"_ 

**2 issues have been discovered  (and solved) while developing:** (see at the end of this comment for a more detailed explanation)
Screencast for the final result:
https://drive.google.com/open?id=1Icu-2m5aJPwS_-fMWxyFh1VuzT868tPX


**Issue 1**
**Description:** A developer's warning regarding non valid html5 nesting. 

**How to reproduce:**
- In the "Compare tool (http://mediasuite-test.rdlabs.beeldengeluid.nl/tool/query-comparison)" 
- Select any query and click the COMPARE button
- On the graph switch to Relative view.
- Hover over the graph and the warning will be display in the 'Console'
- The result is: 

![Screenshot 2019-01-22 at 06.38.33.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/a8398cbd-d8e9-40da-b64b-467f75ea6b65)

**Issue 2**
**Description:**  No data displayed in graph when updating selected queries.  

**How to reproduce:**
- In the "Compare tool (http://mediasuite-test.rdlabs.beeldengeluid.nl/tool/query-comparison)" 
- Select any query and click the COMPARE btn.
- On the graph switch to Relative view.
- Update the selected query/ies and click the COMPARE button 
- The result is:

![Screenshot 2019-01-22 at 06.50.40.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/3cb9dd38-8ec4-462d-988b-68a4b29be35b)

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
As discussed earlier with @lilimelgar the issue with the dots not being displayed in the lineChart in the comparative tool has been solved in this last update.

**@lilimelgar :** Please take a look at that in the labo-components branch :
task/#166-add-histogram-to-comparative-tool

![Screenshot 2019-01-28 at 16.09.41.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/6460f091-45b2-4537-b4b4-e27a72eece0e)

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Issue done in labo-components branch task/#166-Add-histogram-to-comparative-tool.

Since new javascript features have been enabled and used in this branch a "npm run install" is required.
This  branch also fixes issue reported in https://app.zenhub.com/workspace/o/beeldengeluid/labo-components/issues/272
Both issues have been moved to q/a and this branch is the one that deals with both tickets/issues.

**Comment by avlisodraude** [comment]
@lilimelgar @jblom :

The issue reported by @lilimelgar regarding wrong selected queries being selected in the comparison tools has been solved in the last commit from labo-components branch _"task/#166-Add-histogram-to-comparative-tool"_

https://github.com/beeldengeluid/labo-components/commit/946a422140a83f813fb048715656cb5284cfb1bb

@lilimelgar : The issue is in q/a. Please check that the changes fixed the issue and comment.

**Comment by lilimelgar** [comment]
@avlisodraude Tested in branch task/#166-Add-histogram-to-comparative-tool
I tested using user project "issue 166 queries test" with 1) a query for "klimaatverandering" in radio and television (all metadata, no date range), and 2) "Pim Fortuyn" in KB (Ocr) and BG audiovisual (metadata) in date range 1991-1995.
Since somehow searching in ASR doesn't work in this branch, so, I didn't test with these data). 
With the test above, all features and data look OK. 
-Please check issue with triplicated date field, when fixed: Ready for pull request.

**Comment by lilimelgar** [comment]
@avlisodraude Tested again. It's ready for pull request.

There is a minor improvement that I would suggest to add to this branch, but feel free to close this issue and let me know if I should add a new one for it: In the popup now you see the list of queries with the colours, when there are many (see image below), it may be difficult to know to which query the value belongs to. Also, since relying on colour information may be problematic in some cases, it would be ideal to add a query number (and use it also in the query boxes). So, in the query boxes it will show like this:
Q1 Title: ...
Q2 Title...

And in the popup:
Q1: number
Q2: number

![screen shot 2019-02-05 at 18 59 16](https://user-images.githubusercontent.com/8133228/52293922-490e5080-2978-11e9-8464-8c643bf617e4.png)

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Issue updated to fix 'collateral damage' caused by records without queryID.
The following screencast will show the behaviour regardless the lack of queryIDs for some queries already saved in the workspace:

https://drive.google.com/open?id=1wO2Wkh8UCmx00J3eTKH1xJBUZtPfNHtC

**Comment by jblom** [comment]
@avlisodraude alright I finished the code review. It should be mostly ok now code-wise. Functionality-wise, I tested mostly in the same manner as shown in the screen cast, but did not really look at the correctness of the data.

If @lilimelgar is fine with this, I will merge the code, so we can move on :-)

**Comment by jblom** [comment]
@avlisodraude I already made & linked the PR for this issue

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Issue already merged. So I will close it.

**Comment by jblom** [comment]
@avlisodraude @lilimelgar it's all good so closing!
