### ISSUE TITLE
As a user I would like to see "highlighted" the individual words from my Boolean query in the search results

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#170]
@lilimelgar commented on [Wed Mar 21 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/346)

The search term is highlighted when it is only one, not the individual words of the boolean query.

Acceptance criteria:
- when searching for e.g. "amsterdam arena" AND "de kuip", both "amsterdam arena" and "de kuip" should be highlighted in the search results.
- when searching for e.g. amsterdam bloemenmarkt AND rotterdam bloemencorso all individual words should be highlighted as well as the phrases on each side of the boolean expression. This means the following should be highlighted (if present): "amsterdam", "bloemenmarkt", "amsterdam bloemenmarkt", "rotterdam", "bloemencorso" and finally "rotterdam bloemencorso"

**Comment by jblom** [comment]
@lilimelgar this was tested and merged into master. Could you test?

**Comment by lilimelgar** [comment]
Tested in Master. The examples included in the acceptance criteria work well when the user doesn't select a field cluster (i.e., searching in "archive's metadata"). But, ideally, the highlights should also work when a field cluster is selected. For example, the query:
(koe AND varkens) OR boerenleven
Using the "titles" field cluster should give a highlight of "boerenleven" in this result:

![screen shot 2019-01-09 at 17 06 46](https://user-images.githubusercontent.com/8133228/50911839-f9983b80-1430-11e9-9f06-8145f0316279.png)

I can add more examples for testing later.

**Comment by jwassenaarbg** [comment]
@lilimelgar Whilst fixing another issue with the highlight regex I also found the issue with above example. It has been fixed but not yet pushed.

**Comment by lilimelgar** [comment]
@jwassenaarbg Just in case, there are some comments additional to this issue in #217 which I just closed.

**Comment by lilimelgar** [comment]
Test in progress using branch iss_250_quickviewhighlights. Liliana will let Johannes know when the test is finished.

Using three cases:
-Single word
-Two words
-Search expressions with boolean operators "" AND:
a) "amsterdam arena" AND "de kuip"
b) "economische crises" AND "culturele identiteit"
Each case has been tested with the different search options (e.g., for B&G audiovisual collection):
-No field cluster is selected
-Titles field cluster
-Descriptions field cluster
-Keywords from subtitles field cluster
-Subject keywords field cluster
-ASR cluster
-Custom field cluster

Preliminary suggestions:
- [ ] In the search result snippet here below. Instead of saying "0 matches" (which is confusing for the user since they have found this result, present two options:
0 matches in the metadata - 10 matches in the enrichments

**Comment by jwassenaarbg** [comment]
Hey @lilimelgar we don't have access to the enrichments there, which is why some results show 0 matches. ElasticSearch has access to the ASR and found results in there, which is why they show up and still have 0 matches. Rewriting it to "matches in the metadata" is more clear so that part can be done.

**Comment by jblom** [comment]
@lilimelgar & @jwassenaarbg I've changed the label to "x match(es) in metadata" (so you have to git pull in branch iss_250_quickviewhighlights. This branch also serves #250)

@lilimelgar could you finish testing this issue + #250, so Johannes can make a pull request? I'd really love to have these nice features on board. 

Also I can do some styling during the pull request (i.e. code review), since that is a bit crude in some places.

**Comment by jblom** [comment]
@lilimelgar so all the stuff in the pop-up, i.e. issue #250 you also checked? If so I'll restyle a bit and merge.

Showing the amount of hits in the ASR is not possible right now. It would be a good requirement when we would have an EPIC for optimising the performance/stability of the (ASR) search in the search API repo.

**Comment by lilimelgar** [comment]
@jblom Yes, also tested issue 250, I was wondering if that was in a separate branch, but I see it's in the same one. Everything works well! Just one small suggestion before closing this one:

In the popup, the label that says now "Highlighted term(s) has to be more precise, my suggestion: "Matches in the archival metadata:"
