### ISSUE TITLE
As a developer, I need to fix issue with bookmark ordering options in the Workspace

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#173]
@lilimelgar commented on [Wed Oct 10 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/515)

This issue has two parts:

Bug. Fix issue with ordering options: the bookmarks in the workspace (user project) can be ordered accordingly to different criteria. There seems to be a problem though when switching between options (the first selected option sticks). See [screencast](https://drive.google.com/open?id=1f1Zn5HdkdTWuW68csJI7JiZRKhAcXC1o).

---

@avlisodraude commented on [Thu Nov 01 2018](https://github.com/CLARIAH/wp5_mediasuite/issues/515#issuecomment-434953658)

@lilimelgar @jblom 
issues (so far): 
Table default sorting to "Bookmark created" (for which there is no column available) so it lead users to believe that the DATE column is the one affected by this sorting (DATE = record created). 

Maybe this default sorting can be removed from the 'selection list' since user can sort by group or other criteria already available?

"MEDIA" column sorting breaks when no media value is present in record showing a Javascript error (BookmarkTable.jsx:248 Uncaught TypeError: Cannot read property 'length' of undefined).

Sorting by "Oldest/Newest objects first" doesn't sort properly the DATE column.

Note: Some 'data sanitation' needed before filtering since object's DATE field comes (as found so far) as either: 
-- dd-mm-yyyy
-- range (year1-year2) 
-- no Date  when there is not object recognized (undefined)  (Could not reconsile with source catalogue)   
-- null

**Comment by avlisodraude** [comment]
@lilimelgar @jblom :

Issues: 
MEDIA column sorting breaks when no media value is present in record showing a Javascript error Cannot read property 'length' of undefined). 
Now a check to be sure that the object exists is done.

Because Date format not being sanitized Sorting by "Oldest/Newest objects first" doesn't sort properly the DATE column.

Examples of date formats found:

open-beelden-eye
1913-01-01
id: "dd93bd6b-8aa3-465e-9a3c-e1df16fbecf4"

"dans-oral-history"
id: "oai:easy.dans.knaw.nl:easy-dataset:50198"
"2012-06-05"

"dans-oral-history"
"2016"

dans-oral-history 
2016
oai:easy.dans.knaw.nl:easy-dataset:64205

"nisv-catalogue-aggr-full-18-158"
id: "4650154@program"
"16-08-1996 / 16-08-1996"

eye-desmet-papers4 
1921-1923
MMFMA01_PM_008065

"eye-desmet-films"
"1911  ([circa])"
id: "FLM4636"

"eye-desmet-films"
date: "1910 - 1919  ([circa])"
id: "FLM43941"

"nisv-catalogue-tv"
date: null
dateField: null
id: "5268418@program"
PS: even though date is available in itemDetails. 

dataset: "eye-desmet-affiches"
date: "1910 - 1919  ([?])"

Changes done to CollectionConfig and mapping files

**Comment by lilimelgar** [comment]
I tested in Master, @avlisodraude: still some dates show incomplete and/or with text, see:
![screen shot 2018-11-22 at 15 19 37](https://user-images.githubusercontent.com/8133228/48908224-f5f12b00-ee69-11e8-9d8a-34f4cd06f41f.png)

![screen shot 2018-11-22 at 15 20 07](https://user-images.githubusercontent.com/8133228/48908251-05707400-ee6a-11e8-8cfc-5b0bb7d6ec51.png)

When ordering, there are still some issues:
-The B&G Radio collection, and the B&G Television collection, don't display any dates in the Workspace
![screen shot 2018-11-22 at 15 21 42](https://user-images.githubusercontent.com/8133228/48908324-3cdf2080-ee6a-11e8-947e-4aa6f9c12e5c.png)

-The items from B&G audiovisual collection don't get ordered in a proper way, they go to the bottom:
![screen shot 2018-11-22 at 15 22 01](https://user-images.githubusercontent.com/8133228/48908386-6009d000-ee6a-11e8-8b6a-fa34f492c830.png)

**Comment by avlisodraude** [comment]
@lilimelgar 
Issue update in labo-components branch __"task/#173-bookmark-sorting"__

**Comment by lilimelgar** [comment]
@avlisodraude. I tested in the branch "task/#173-bookmark-sorting". There are also some issues persisting in the ordering, see for example:
![screen shot 2018-12-11 at 17 08 49](https://user-images.githubusercontent.com/8133228/49813378-a36ba600-fd67-11e8-9428-61025d65995e.png)

@jblom Even though Eduardo made improvements to the display of dates in the workspace, I think we should look at this issue more in detail, to see if we should normalize/clean the dates for the data more consistently instead of doing the fixes in the workspace. Shall I close this one and add a new issue for a better check? or do we keep this one open for the next sprint?

**Comment by jblom** [comment]
@lilimelgar @avlisodraude I'd say we keep this one, but properly write a new description and acceptance criteria. The description now hasn't been cleaned up anyway. I add the label "requirements needed"

**Comment by lilimelgar** [comment]
@jblom The requirements for this issue are mostly related to cleaning the data itself, perhaps it's better to write a new issue for the importer repo? What I suggest is that we check and try to clean the default date field of each collection in the MS, creating a normalized date field that will be used here. This was already done for Desmet films, papers and posters. These are the other date fields to normalize:
--For B&G (audiovisual, radio, television) collections: Program=Sortdate-in publications
--For the Desmet Film collection: productiejaar
--For the Desmet Poster collection: jaar
--For the Desmet paper collection: mostSpecificYear => folder
--For the KB newspapers collection: dc-date (to confirm with Willem please)
--For the Open Images (EYE) collection: dcterms-date
--For the Open Images (B&G) collection: dcterms-date
--For the Oral history collection: dcterms-created

**Comment by jblom** [comment]
@lilimelgar yes good idea. I'm getting tired of these date issues and since we have a generic processing unit ("the updater") in the importer for this, let's make a story where we'll make sure to have one proper date field (with proper dates) for each collection. (first checking if you did not make this story already)

**Comment by jblom** [comment]
@lilimelgar ok I've created a new issue for this in the importer. Could you check the criteria/description as well? https://github.com/beeldengeluid/labs-importer/issues/19

**Comment by lilimelgar** [comment]
@jblom I checked the criteria in the issue above and commented there. I'll close this one for now. I will add to the Documentation pages that the date fields in the Workspace may not work fully properly when ordering.
