### ISSUE TITLE
As a developer, I need to solve a bug in the NISV Television collection

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#211]
Where: the NISV television collection

Problem:
When browsing the results of and going to the last page, there is an error in reading the resource ID. Thus, no records from the last page can be viewed.
How to reproduce:
-Open Search tool
-Load NISV Television collection
-Search by, for example, "Pim Fortuyn"
-Go to the last page of results

This is the error:
![Screen Shot 2018-11-21 at 16.14.04.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/f7584b78-6d79-4504-be7e-b8283b539ebf)

@avlisodraude Please check what the cause is, and add "approach" to solve the issue

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
To extend over the description this issue affects not only the "Television Collection" but every collection and as Liliana pointed out the easiest way to reproduce it is to select any collection jump to the last page and select the last record to view it in the item-details page. Once you try to click the previous btn ("Previous resource") the page crashes since there is no resourceId assigned for that item.
**Cause** 
In the ItemDetailsRecipe (L:817-L:820) the function does not returns the correct id in that specific situation -- guilty as charge ;-)  --
**Solution:** 
I modified the prevResource logic so now it gets the correct resourceId.

**Branch** (labo-components):
bug/#211-issue-assigning-resourceId-to-previous-btn

**Comment by avlisodraude** [comment]
@lilimelgar  Same issues as 212.

**Comment by lilimelgar** [comment]
Tested in Master, solved :)
