### ISSUE TITLE
As a user I want to know when my search won't be able to be executed

### ISSUE THREAD

**Issue by avlisodraude** [beeldengeluid/labo-components#228]
When I try to go to the last page in the single search tool in big result sets no query is being executed and the user only sees a blank search hits section.
As a user I'd like to get notified the reason for this and some recommendation on how to get results (refinement the query).

**To reproduce:**
- Go to the single search
- Select the "Audiovisual Collection" from the collection selector
- Then search for "Amsterdam"
- Click the last page button

**Result**
The user will get a blank results set page and in the console a message informing:
 _"Currently the search engine cannot look beyond this point, please narrow your search terms"_

**Acceptance criteria**
- [x] Display a message to the user explaining the cause for this issue and advising him/her to refine the search criteria.

**Comment by jblom** [comment]
@avlisodraude this issue looks well-defined. Let's keep it in the backlog for now

**Comment by avlisodraude** [comment]
@lilimelgar  @jblom :

Issue done in labo-components branch _"task/#228-set-out-of-bounds-search-message"_

**Comment by lilimelgar** [comment]
Tested in branch above with B&G collection, KB newspapers, and DANS OH collections. Almost all OK, only two questions/suggestions:

(1) @jblom Since we have very curious scholars about how search engines work, could you please explain a bit more, or provide a reference to ES perhaps? in the message why the search engine cannot go beyond this point? 

(2) @avlisodraude Ideally, if the user finds this window below, search should work again if they hit in the search box using the same terms that were there:
![screen shot 2019-01-16 at 16 15 40](https://user-images.githubusercontent.com/8133228/51258323-02958980-19aa-11e9-8543-3b902f5c6ced.png)

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

Regarding last comment from @lilimelgar (two questions/suggestions):
1. @jblom will add a proper message when merging that branch 
2. Issue already corrected.

There is already a pull request for this issue:
https://github.com/beeldengeluid/labo-components/pull/257

**Comment by jblom** [comment]
@avlisodraude @lilimelgar pull request #257 was too old to easily merge. Instead I put the code for showing the out of bounds message directly on master, so you could test it there. The message looks like this: 

<img width="1162" alt="schermafbeelding 2019-01-28 om 09 53 54" src="https://user-images.githubusercontent.com/917310/51824512-bf5ce400-22e2-11e9-8a5a-6358b08f3385.png">

If all is ok, please close this issue. Otherwise just mention whatever is lacking in this issue.

**Comment by avlisodraude** [comment]
@jblom @lilimelgar 
I checked/tested Jaaps' changes from Master and everything works fine as expected.

**Comment by jblom** [comment]
@lilimelgar could you please test one more time & close this one?

**Comment by lilimelgar** [comment]
Tested in Master, all OK :)
