### ISSUE TITLE
As a developer, I need to update the "Total" value of the metadata fields in the Inspector tool

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#234]
Where:
In the Inspect tool

What the problem is:
-The total value is showing the same value as the "present" value:
![Screen Shot 2018-12-10 at 11.44.52.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/a2b0ff97-f548-4571-836b-9d5396470daa)

Acceptance criteria:
- [ ] The Total value should be the sum of the "present" + "missing" fields

**Comment by jblom** [comment]
@lilimelgar added to backlog

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

Bug fixed in labo-components branch _"bug/#234-update-field-total-in-barchart"_
Since this is a minor fix I already created a pull request _"https://github.com/beeldengeluid/labo-components/pull/240"_

The next screencast shows the graph displaying the correct total amounts:

https://drive.google.com/open?id=1MCLN_QvKT3UQjjJsNPlQcZfskh6aRvjF

**Comment by jblom** [comment]
@avlisodraude @lilimelgar merged & tested & closing, since it's such a small thing
