### ISSUE TITLE
As a developer, I need to have consisten icons for bookmarks

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#235]
Where: In the Workspace, in several places:

**1) Bookmark view**
![Screen Shot 2018-12-11 at 16.40.54.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/d77eb983-2208-4ca9-8cda-048ec0412f08)

**2) Annotation view**
![Screen Shot 2018-12-11 at 16.47.53.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/2c3f48c0-3ece-4eee-b586-58ac755431ff)

Approach:
Use the same icon as in the Search tool and Resource viewer:
![Screen Shot 2018-12-11 at 16.42.22.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/82c15439-6fc3-4172-95ee-1ceb69b780b6)

Acceptance criteria:
- [x] The icon is changed in the Workspace, Bookmark view, here:
![screen shot 2018-12-11 at 16 51 00](https://user-images.githubusercontent.com/8133228/49812327-761df880-fd65-11e8-8fdd-de5b0af322ec.png)

- [x] The icon is changed in the Workspace, Annotation view, here:
![screen shot 2018-12-11 at 16 56 58](https://user-images.githubusercontent.com/8133228/49812479-ce54fa80-fd65-11e8-8c59-936c7a4a1569.png)

- [x] The icon is changed in the Workspace, Annotation view (Codes, Comments, Links, Metadata cards), where it shows like this:
![screen shot 2018-12-11 at 16 57 41](https://user-images.githubusercontent.com/8133228/49812516-eaf13280-fd65-11e8-873b-4b103d2d005e.png)

- [x] In addition, delete the star icon (don't add any icon) to the Codes, Comments, Links and Metadata Card filters in the Annotation view. E.g., where it shows like this:
![screen shot 2018-12-11 at 16 55 51](https://user-images.githubusercontent.com/8133228/49812421-b1b8c280-fd65-11e8-8ba3-be27790736ab.png)

**Comment by jblom** [comment]
@lilimelgar makes sense, put this one in the backlog

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 

**Issue done in labo-components branch:**
task/#235-consisten-icons-for-bookmarks

**Regarding the approach for the Acceptance criteria:**

__(*)__  
>"The icon is changed in the Workspace, Bookmark view, here: ..."

Since the Group selection box in the Bookmarks tab was the only one with an icon (__(1) Bookmark view image__) I have considered more consistent to remove it instead of replacing it with the new bookmark icon so every selection box will have the same format (just a label before the corresponding selection box).

>"The icon is changed in the Workspace, Annotation view, here: ..."

It's been replaced by the corresponding bookmark icon :
![Screenshot 2018-12-17 at 14.09.16.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/d32d6eab-fdd9-4e04-bb55-0c7cc44b5697)

>"The icon is changed in the Workspace, Annotation view (Codes, Comments, Links, Metadata cards), where it shows like this: ..."

>"In addition, delete the star icon (don't add any icon) to the Codes, Comments, Links and Metadata Card filters in the Annotation view. E.g., where it shows like this: ..."

 Same principle as in the first Acceptance criteria point __(*)__

**@lilimelgar:** Please test that issue in the already mention branch and make your comments so I can modify to comply with the original criteria or create a pull request.

**Comment by jblom** [comment]
@avlisodraude I like how it looks now. @lilimelgar can you check & close? Then I'll merge it with master

**Comment by lilimelgar** [comment]
@jblom I tested this in the branch, all OK with the icons, you can merge it with master.

**Comment by jblom** [comment]
@lilimelgar ok done
