### ISSUE TITLE
Weird grey hover over effect in collection inspector bar chart when field analysis has 0% results

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#242]
It's easy to reproduce by selecting the "EYE Desmet Film" collection, followed by the "Affiche" field and the "msDate_ReleaseDatum Nederland" as date field. When you then hover over the graph, you see a grey square, which does not look appealing:

![Schermafbeelding 2018-12-18 om 12.58.37.png](https://images.zenhubusercontent.com/5a127cc38a75884b90880fdc/a1f0b29e-7d7c-4af1-b78d-4a1131187e32)

![Schermafbeelding 2018-12-18 om 12.58.24.png](https://images.zenhubusercontent.com/5a127cc38a75884b90880fdc/331f32be-b2b4-40c7-bea1-95c9a035c492)

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Issue solved in labo-components branch:
__issue/#263-dont-show-graph-when-no-data-available__ 

Solution:
Since this issue is related to the lack of data (along with @lilimelgar ) we decided that the best solution is to no display a graph and instead a proper message to the user as shown below:
![Screenshot 2019-02-05 at 10.18.02.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/e13a21aa-ca1b-4e34-a33d-4291ac9d9949)

**Comment by jblom** [comment]
@avlisodraude @lilimelgar ah so this one can be closed? I already merged issue #263 .

If so please closeeeeeeee
