### ISSUE TITLE
As a user, I want to see which queries failed in the comparative search, so I don't have to wonder why not all my selected queries are visualised

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#253]
Sometimes old saved queries refer to an index that no longer exists. In those cases that query will never work again. On the comparative search it would be nice to show which of the selected queries (selected for comparison) return an error response.

**How to reproduce**
- select Testproject-Issues-Liliana
- select the query with issue501 
- when running the comparison, you can see that the call to the CKAN collection_info returns a resource not found.

<img width="774" alt="schermafbeelding 2019-01-14 om 13 46 13" src="https://user-images.githubusercontent.com/917310/51113599-c96ee500-1802-11e9-9569-8cd6994e8a87.png">

<img width="1192" alt="schermafbeelding 2019-01-14 om 13 35 37" src="https://user-images.githubusercontent.com/917310/51113220-9ed05c80-1801-11e9-824c-8e08820a0d91.png">

<img width="1197" alt="schermafbeelding 2019-01-14 om 13 35 45" src="https://user-images.githubusercontent.com/917310/51113223-9f68f300-1801-11e9-8a77-9913a617a042.png">

**Comment by lilimelgar** [comment]
@jblom: after testing issue #166 with @avlisodraude we found out that the reason for some queries to not work properly is that they were created before a bug in the saved queries was fixed (September 2018: https://github.com/CLARIAH/wp5_mediasuite/issues/501). What we think the best solution would be to avoid users making crash the Compare tool is to delete all the saved queries before that date. Since those old queries cannot be deleted manually, I could delete all user projects that were made for testing. Please let me know if this is a good solution, since in that case I should check if there are "real" user projects made by scholars, and notify them in Gitter that we will delete them.

**Comment by jblom** [comment]
@lilimelgar I agree we have to delete the bad data. However I want to use this opportunity to implement an extension to the workspace API that allows the user to delete all annotation related to that project as well. 

In any case, please wait with the deletion of these items until we've talked about it in person

**Comment by lilimelgar** [comment]
@jblom Can we talk about this one? ;)

**Comment by jblom** [comment]
@lilimelgar @avlisodraude I think this issue is solved for now, since I added information to the query boxes:

![Schermafbeelding 2019-04-24 om 08 27 44](https://user-images.githubusercontent.com/917310/56637035-ed945a80-666a-11e9-9f6b-0e1c0ea74b28.png)

I suggest closing this one and talk about the bigger issue (cleaning old data, improving the workspace etc) in another issue (or epic)

**Comment by lilimelgar** [comment]
@jblom I could not test this in production since my old data (with old queries) is not accessible anymore after my UvA account was deleted. But I tested in the test version (mediasuite-test...), with the user project that has the oldest data ("Liliana test Jan 24"), and with user project: "Testproject-issues-Liliana", it all worked well, and I got a message "This query coulnd not be executed" for an old query.
Question: Could you please create the Epic/issue for cleaning old data and improving the Workspace on that aspect? I wouldn't know exactly what criteria to add. Then, please close this one :)

**Comment by jblom** [comment]
@lilimelgar thanks for testing. I've created https://github.com/beeldengeluid/labs-user-space-api/issues/7 to fix the corrupted queries.
