### ISSUE TITLE
As the B&G ICT manager, I want to prevent users to be able to play the off-air content of items in the catalogue

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#270]
Since it is impossible to request a partial stream, the player has to be adapted to avoid playing/viewing of-air content.

**Approach** 
Try out if the use of media fragment URLs solves the problem. If so, figure out if this solution works for all players (HTML5, YouTube, Vimeo) and all important browsers

**Acceptance criteria**
- [x] media suite video player only shows the on-air content (and prevents skipping to it)
- [ ] same thing for the audio player 
- [x] make sure all components tied to the player still work, since they rely on the time codes related to the video
- [x] the user cannot see ASR transcripts of off-air content
- [x] make sure annotations are still created accurately (with proper time codes)

**Comment by jblom** [comment]
Note: currently the video starts playing from the start when switching back and forth between full-screen and normal mode.

**Comment by jblom** [comment]
**Note**: media fragments turned out to be useless, since it only enables one to jump to a different starting point in the video without limiting controls or anything

**Comment by jblom** [comment]
**Note**: in Safari full-screen mode looks terrible and needs to be fixed. In Firefox playout via HTTPS using my self-signed certificate does not work, even though it is trusted by my mac and listed in the list of trusted certificates in FireFox settings...

**Comment by jblom** [comment]
**Note**: full-screen in Chrome is also not fully correct. The video is not fit to the screen yet

**Comment by jblom** [comment]
@lilimelgar this is ready for testing. It should work in both Chrome & Safari. For Firefox there is still the SSL certificate related issue that prevents play-out from working.

Also now you should only see the custom controls for collections with off-air content (only B&G) and in those cases only for video.

There are many things to check, so take on this story when you have proper time

**Things to check:** 
- are you able to navigate to the off-air content (this should be a negative)
- does the transcript show off-air transcripts? (this should be a negative)
- does annotation still work properly? (note that all the timelines had to be adjusted as well)
- does segmentation still work properly? (also check the segmentation input fields next to the player)
- does switching to full-screen work properly
- do the controls work properly in full-screen
- do the volume controls work as expected

**Comment by jblom** [comment]
@lilimelgar also added fixes to the "tracks" to this branch and now I'm showing the segments in a more human readable way (note that there is much to say/do for the styling & location of this new segment list):

<img width="653" alt="schermafbeelding 2019-02-20 om 17 18 38" src="https://user-images.githubusercontent.com/917310/53106683-d84c6400-3533-11e9-84cc-002583a40e21.png">

now you see it's located below the player:

<img width="737" alt="schermafbeelding 2019-02-20 om 17 20 59" src="https://user-images.githubusercontent.com/917310/53106757-f619c900-3533-11e9-8c0c-e4bbe1a25c5e.png">

**Comment by avlisodraude** [comment]
@jblom :
After some testing I found an issue regarding mismatch times displayed between the video being played and the transcript itself, for example:
http://localhost:5304/tool/default-item-details?id=4272263@program&cid=nisv-catalogue-aggr-full-18-158&st=%224272263@program%22#

![Screenshot 2019-02-25 at 16.18.38.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/83028df4-f0fa-4e97-85aa-56c5c526884a)

**Comment by jblom** [comment]
Thanks for testing @avlisodraude! Point 2 & 3 are now solved in the master. I'll now checkout point 1

**Comment by jblom** [comment]
@avlisodraude @lilimelgar I've fixed the transcriber codes & broken auto scroll as well. It's in the master. Please test

**Comment by lilimelgar** [comment]
Tested in the Test version (http://mediasuite-test.rdlabs.beeldengeluid.nl) on March 4, 2019. Not in Master branch since there was a connection error (see image below). Tested with the videos below (trying to get off-air content at the beginning and end). These are the detected issuest:

- [ ] does the transcript show off-air transcripts?  *at the end of the broadcast* (this should be a negative): Not for all videos but for some this is not met. Check for example these items, at the end of the ASR there are some words but not sure if this is an off-air ASR line:
-eenvandaag-20140527	EENVANDAAG___-WON01244845 (see image below)
-nieuwsuur-20160404	NIEUWSUUR____-WON01637922. (oh)
-eenvandaag-20080626	EENVANDAAG___-WON00381819 (ja)

- [ ] There are some synchronization issues with ASR at the end. Three examples:
-netwerk-20061030	NETWERK______-WON00174031. The very last line of the ASR was not played together with the audio/video, and it was not possible to navigate to the very last closing sentence using the ASR ("En vanavond kunt u voor achtergronden al terecht bij de collegas van nova na het journaal van tien uur."). When trying to make an annotation to this fragment, the saved fragment didn't play back but jumped to the beginning of the video. 
-Here the problem is more clear, the entire closing sentence is not synchronized: jeugdjournaal-20151031	NOS_JEUGDJOUR-WON01547456
-Similar issue happens here: pownews-20110923	POWNEWS______-WON00727182.

**And a few things to fix/improve:**
- [ ] The play button should be used the other way around (pause when the video is playing, and play when the video is paused)
- [ ] Not sure if this was like this before, but now when clicking on an ASR sentence, the content only plays when clicking on the play button, if I remember correctly, it used to play immediately
- [ ] Scape key should work for leaving full screen view

---Screenshots and examples ---
**Problem when trying to use Master branch**
![screen shot 2019-03-03 at 12 24 42](https://user-images.githubusercontent.com/8133228/53712929-3ab53680-3e49-11e9-98ed-047683cf0c9d.png)

**Videos used for testing** (suggested by Hugo Huurdeman)
nieuwsuur-20151116	NIEUWSUUR____-WON01557675
nieuwsuur-20160404	NIEUWSUUR____-WON01637922
eenvandaag-20080626	EENVANDAAG___-WON00381819
eenvandaag-20140527	EENVANDAAG___-WON01244845
eenvandaag-20160624	EENVANDAAG___-WON01683220
netwerk-20061030	NETWERK______-WON00174031
pownews-20110923	POWNEWS______-WON00727182
jeugdjournaal-20151031	NOS_JEUGDJOUR-WON01547456

**Off air content in the ASR at the end of the broadcast**
![screen shot 2019-03-04 at 07 14 15](https://user-images.githubusercontent.com/8133228/53714004-270bcf00-3e4d-11e9-8256-3340ce8ec3de.png)

**Comment by jblom** [comment]
@lilimelgar I've tackled all of the issues, I think. As to your remark on the clicking of a sentence: this always was like this: if the player is paused, it will stay paused; if the video is playing, it will stay like that as well.

**You can test now**:
- the off-air transcript at the end is no longer showing, there was indeed a small bug there
- the ESC button (for leaving full screen)
- when clicking the last line, the highlight should not jump to the first line anymore

**Comment by lilimelgar** [comment]
@jblom It all works well! Tested in master. Only two things to check/fix:
- [ ] The navigation buttons are not there anymore in the resource viewer
![Screen Shot 2019-03-18 at 12 05 17](https://user-images.githubusercontent.com/8133228/54526198-54409d00-4976-11e9-9851-cd0e593567b6.png)
- [ ] The play/pause button in the video only shows "pause" and doesn't switch to play when paused

**Comment by jblom** [comment]
@lilimelgar I cannot reproduce this. If you can, please report it as a new bug. Yay the rest works! I'm closing this one!
