### ISSUE TITLE
As a developer, I have to fix the bug that shows an incorrect date field percentage in the collection inspector

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#281]
**How to reproduce**:
- select the B&G audiovisual collection
- select a field from the field selector
- select the "enddate (in: recordings) | segment", which shows 0% presence in the collection

After selecting this date, the bar chart does show values for different years:

![Schermafbeelding 2019-02-05 om 14.14.46.png](https://images.zenhubusercontent.com/5a127cc38a75884b90880fdc/5ac1c384-4b52-4429-b0d4-8b96db5f80da)

If you check the statistics at the bottom however you can see that the date field should have some values:

![Schermafbeelding 2019-02-05 om 14.23.07.png](https://images.zenhubusercontent.com/5a127cc38a75884b90880fdc/6eb8b81e-fffa-4c4f-acc3-6c920f7ae24f)

Also wrong is that: in the bar chart you can identify **6 bars** (with value 1) while the statistic say that only **5 documents** should have both the date field and analysis field present...

**Acceptance criteria**:
- [x] fix the display percentage in the date field drop-down
- [x] investigate & fix the difference between the chart data and the statistics at the bottom

**Comment by avlisodraude** [comment]
**@lilimelgar @jblom**
 
Issue has been done in labo-components project, branch:
_issue/#281-bug-incorrect-date-field-percentage_

**Screencast with issue description:**

https://drive.google.com/open?id=1zJEBVQ0eu5AmfQ9L5O3Ykk-wXA7RGHSW

**Solution:**
Since the issue was not a lack of data but more a Math rounding problem the solution consisted in modifying the function that 'formats' the percentage before it gets saved into 'session storage'

**Test**
1. Remove session storage from the current browser session (or use incognito mode)
For removing session storage check next screencast : https://drive.google.com/open?id=1_R4ElGS3qxAAMgmWWhF9OUrxaXTvsCDA
2. Switch to _issue/#281-bug-incorrect-date-field-percentage_ branch
3. npm run prod

**Expected result**
 Screencast : https://drive.google.com/open?id=1If9ef4Tj2-oHThTe15VKfqQqQermBQUV

**Issue status**
Since this is a bug and the fix is a small change to the code plus is fulfills acceptance criteria, I've created a pull request:
https://github.com/beeldengeluid/labo-components/pull/294

**Comment by jblom** [comment]
@avlisodraude since it was a really small change, I merged it right away. I'm sure that fixes the problem. I'll test it today.
