### ISSUE TITLE
As a developer, I need to fix the highlights in the ASR text when the wild card operators are used

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#297]
Where: Resource viewer, ASR interactive transcript.

Problem: If a user searches using a wildcard such as ? (e.g., soeraba?a), the highlight shows a duplicated letter, like this: 
![Screen Shot 2019-02-20 at 16.07.57.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/71790439-3092-4c40-b32c-ee4907bea607)
While in the ASR transcript, the word is this:
![Screen Shot 2019-02-20 at 16.07.47.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/bf58bb1f-97d6-443e-87f0-63754140b456)

Acceptance criteria:
- [x] The highlighted word in the interactive transcript should be the complete word from the query, not including the wildcard operators (*  ?)

@jblom: sorry since you said you didn't want to see more the highlights issue ;), but do we also have to check other highlighting rules for the ASR interactive transcript based on [#170](https://github.com/beeldengeluid/labo-components/issues/170)?

**Comment by jblom** [comment]
@lilimelgar assigned it for this sprint: Geronimooooo

**Comment by avlisodraude** [comment]
@lilimelgar @jblom :

Issue for labo-components project done in branch __issue/#297-bug-fix-highlighted-words-in-transcript__

**Test**
In labo-components project
`git fetch`
`git checkout issue/#297-bug-fix-highlighted-words-in-transcript`
`npm run prod`

Clear browser CACHE

**Screencast**
https://drive.google.com/open?id=1eyrQsqxYjrXvUbiqIHu3Mef7ogPvJ39L

**@jblom @lilimelgar** 
Since this is a bug I already made a pull request __https://github.com/beeldengeluid/labo-components/pull/299__

**Comment by lilimelgar** [comment]
Tested in Master, everything OK!
