### ISSUE TITLE
As a user of the Media Suite, I would like to see the title of the media resource when I am in the Resource viewer

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#301]
Where: Resource viewer
Current situation, users see the carrier ID (screenshot below)
Acceptance criteria: the title of the resource should be displayed instead

![Screen Shot 2019-02-27 at 16.36.26.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/82c66173-0385-438a-b096-7ed33f06702a)

**Comment by jblom** [comment]
@lilimelgar @avlisodraude added this one to the current sprint as it's very simple

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Issue done for labo-components project in branch :
_issue/#301-title-resource-in-player_

**What's been done:**
The current title shown in the FlexPlayer (when in the item details page) corresponds to the assetId. This has been replaced by the title of the current resource.

**Test:**
Using as a reference the item used in the description now we can see that the title is used instead of the assetID

![Screenshot 2019-03-11 at 09.46.21.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/7b19cb15-1766-4182-b07d-69d2490561ec)

**Other examples:**
![Screenshot 2019-03-11 at 09.47.18.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/16ac1ad4-a272-4e8c-9d34-424187021ef4)

![Screenshot 2019-03-11 at 09.45.56.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/145d20a1-c511-44a9-a6ae-6b1de62c47fd)

![Screenshot 2019-03-11 at 09.47.18.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/004f7795-3e7c-4f5f-bfa4-560d4d68718c)

![Screenshot 2019-03-11 at 09.57.56.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/274545d8-55ba-4f73-84c2-1b2e8cb259f3)

![Screenshot 2019-03-11 at 09.56.54.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/68181275-8488-4feb-acf1-561c06c366a3)

**Comment by jblom** [comment]
@avlisodraude @lilimelgar I tested & merged this (since it is such a small thing) I also removed the **Playing:** prefix from the title, since with the media object title it is really unnecessary.
