### ISSUE TITLE
As a user, I want to include the ASR layer when searching without any parameters

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#324]
**Acceptance criteria**
- [x] include ASR when using the search box only (for B&G)
- [x] selecting ASR in the filter options will restrict search to ASR only

**Comment by jblom** [comment]
@lilimelgar @avlisodraude fixed this one in the master. You need the latest mappings for this to work. Check Slack

**Comment by jblom** [comment]
@lilimelgar also deployed on test now

**Comment by lilimelgar** [comment]
Basic test in production with collections that have enrichments: BG, Desmet papers, TV, Radio. I tried simple queries with "metadata" and "all" to see if number of results made sense. I did not do a full test though since this was done before. It all works as expected: more results for All, less for each of the specific clusters/layers.
