### ISSUE TITLE
bug: there is no message anymore for the last page (when it's empty, because it's passed the ES limit)

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labo-components#334]

**Comment by avlisodraude** [comment]
**@jblom** 
Issue done in branch:
_issue/#334-display-outOfBounds-msg_

### Issue:
The error message is never generated since if there's no data the method returns null before even calling that message block.

### Solution
Error message moved to the render method and outOfBounds state's been checked to decide whether or not to generate the message.

### Pull request created:
https://github.com/beeldengeluid/labo-components/pull/337

**Comment by lilimelgar** [comment]
@jblom Small test in production with only one collection, it works well. Shall I test more with all collections? or if it works with one should it work with all?

**Comment by jblom** [comment]
@lilimelgar it should be fine. It has nothing to do with collection specific settings (or else I would be really surprised :-) )So closing this one
