### ISSUE TITLE
As a developer, I want the UI to handle strange characters in search terms

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/labo-components#369]
Searching for a wildcard on its own '*' or the ƒ symbol causes the UI to hang. The Search API returns results ok, so it seems to be an issue with the UI

**Comment by jblom** [comment]
@mwigham thanks for reporting. I put this in the backlog as a bug

**Comment by avlisodraude** [comment]
**@jblom **
Issue done for labo-components project in branch:
_issue/#369-bug-in-singleSearch-with-especial-characters_

A pull request has been created at:
_https://github.com/beeldengeluid/labo-components/pull/387_

### Issue
The app breaks when searching for special characters like '*' or 'ƒ'. 

### Cause
Some characters are part of the regular expression (Escaping, special characters)

### Screenshots
Now special characters don't break the app and they are correctly hightlighted as shown in the following screenshots:

![Screenshot 2019-05-07 at 09.02.11.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/302d50a7-f65f-42fb-bc1f-27bb8d5d1c85)
![Screenshot 2019-05-07 at 09.02.42.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/3193ba0b-e691-47ce-a366-11105c3513da)

**Comment by jblom** [comment]
@avlisodraude I've reviewed the code and changed it quite a bit as you know.

@mwigham I've deployed the changes to test, so could you please test the following (quite thoroughly please):

- [ ] in general: test weird characters to see if highlighting works in the snippets
- [ ] in general: test weird characters to see if highlighting works in the quick viewer
- [ ] in general: test weird characters to see if highlighting works in the transcripts (resource viewer)
- [ ] in general test if phrases are highlighted when a phrase search is done 

- [ ] search for: **ƒ 1.000.000 AND leuzen**: check search snippet & quick view highlighting (boolean operator is NOT highlighted, all characters are properly highlighted etc)
- [ ] search for: **ƒ100**: check search snippet & quick view higlighting
- [ ] search for **"merels en koolmezen"**: check that only the phrase is highlighted
- [ ] search for *****: nothing should be highlighted
- [ ] search for **?**: nothing should be highlighted
- [ ] search for **ƒ**: the character ƒ should be highlighted

**Comment by mwigham** [comment]
Can't test 'search for *****', as the Media Suite keeps searching for a very long time.

Other tests are completed. Mostly it works very well, but I found the following issues:
- words ending in a special character aren't highlighted properly, e.g. when searching for 'België', 'Belgi' is highlighted, for 'café' all  'é's are highlighted, and for 'André' then 'andr' and all 'é's are highlighted
- wildcards upset the highlights, e.g. for 'h*ß' 'h' is highlighted, for 'h?iß' 'hti' is highlighted, for 'muzi*' everything is highlighted
- wildcards also upset the highlights in the transcript, e.g. if you search for '*ñ*' and click on the first hit, then the ASR shows 311 hits, but they are not highlighted
- wildcards also upset the matches found in metadata, if you search on *ƒ* then the highlights are fine, but there are far too many 'matches in metadata' listed
- a one-off strange result: when searching for 'één' in the ASR, I got a hit for 5312337@program, but this showed 0 matches in the transcript viewer

I noticed that the matches in the Quick Viewer are only highlighted in the list of hits at the bottom, not in the text itself, is this intentional?

**Comment by jblom** [comment]
@mwigham thanks for thoroughly testing. I'll put this one back into TODO. After fixing this, it should be pretty robust :-)

**Comment by jblom** [comment]
@mwigham please update the description with new insights gained after making an inventory of possible cases

**Comment by mwigham** [comment]
@jblom isn't that for a new issue? This one was about special characters causing the interface to crash, the new issue would be about determining the desired highlighting strategy for a variety of cases (not just special characters), and implementing it.

**Comment by avlisodraude** [comment]
**@jblom @lilimelgar** 
Issue for labo-components project done in branch:
_issue/#369-filter-special-chars_

Pull request at:
https://github.com/beeldengeluid/labo-components/pull/399

### What's been done?
Refactoring the generateRegexForSearchTerm and escapeRegExp functions to better filter the text to highlight in searchHits and quick view. 
Unfortunately I wasn't able to test it in the transcripts.

### Testing
My testing was done by comparing mediasuite-test agains the working branch using the 'Audiovisual Collection'.

All suggestion made by @jblom on the May 13, 2019 were tested again and the results were successful.

From last comments done by @mwigham on May 17, 2019 

- _Can't test 'search for *', as the Media Suite keeps searching for a very long time._
   No problems when testing on both versions.
- _words ending in a special character aren't highlighted properly, e.g. when searching for 'België', 'Belgi' is highlighted, for 'café' all 'é's are highlighted, and for 'André' then 'andr' and all 'é's are highlighted._
  Issue solved. Now only matching terms are highlighted  
- _wildcards upset the highlights, e.g. for 'hß' 'h' is highlighted, for 'h?iß' 'hti' is highlighted, for 'muzi*' everything is highlighted._
  Issues tested and results work correctly. Especially when adding a wildcard at the end of a search now we don't get the whole text highlighted.
- _wildcards also upset the highlights in the transcript, e.g. if you search for 'ñ' and click on the first hit, then the ASR shows 311 hits, but they are not highlighted. Wildcards also upset the matches found in metadata, if you search on ƒ then the highlights are fine, but there are far too many 'matches in metadata' listed. A one-off strange result: when searching for 'één' in the ASR, I got a hit for 5312337@program, but this showed 0 matches in the transcript viewer._
  Unfortunately because my local branch doesn't display transcripts atm I wasn't able to test these cases.
- _I noticed that the matches in the Quick Viewer are only highlighted in the list of hits at the bottom, not in the text itself, is this intentional?_
  That is correct but it is expected that way.

Also some testing was performed with language characters like: ƒ, ü, ß, ñ,Ö, ä, ö, €

### Screencast
https://drive.google.com/open?id=1LEMQIMEo_4zbbFiULSzGkMNgd-V7SZ2B

**Comment by jwassenaarbg** [comment]
Most issues are solved, code looks good to me.

One question: in line 84 (regexUtil): `const splitTerms = searchTerm.replace(/\s\s\s+/g, ' ').split(" ");`
Why did you put the replace "\s\s\s" there, instead of replacing the "AND/OR/NOT" with "" in the lines above, seems possibly cleaner maybe?

And one issue:
In the comment on line 88 "wildcards are treated as single character pattern". This is not true, as the * wildcard in Elastic Search means "zero or more" characters. So when testing queries like "*markt" or "boeren*". You get examples like "supermarkt" which should be highlighted, but is currently not. My suggestion would be to translate * to any character until a new word starts (space, tab - a dot can't work because if you write google.com then it might go wrong).

**Comment by jblom** [comment]
@avlisodraude @jwassenaarbg 
Also seems that most things are fine (better) now. I also tested the transcript highlighting cases

about line 84: it's strange indeed, but works. I briefly tried changing it like you said, but that didn't work, so leaving it for now...

I think your last comment is a good one for a new issue, so making that and closing this one, since I think it's much better now. 

@mwigham I also deployed this one on test, so you could give it try there as well.

**Comment by mwigham** [comment]
Most of it works fine. Just two minor niggles:

- If you search on h*ß then for the first hit it gives the message 'no matches in archival metadata' - but there is a match in maintitles for one of the segments (if you search on h?iß then it works fine)
- When using * wildcards, only one letter is highlighted as a replacement for the wildcard. E.g. If I search on muzi*, then it highlights 'muzie'. I would expect the whole word to be highlighted.

**Comment by jwassenaarbg** [comment]
Both of these are probably fixed with the new issue @jblom has added. The highligher only highlights 1 character for the *. Thus h*b will not highlight h?ib due to there are 2 characters?

**Comment by jblom** [comment]
@mwigham @jwassenaarbg thanks for checking and I've just extended the new story to also take into account "a star in the middle": #421
