### ISSUE TITLE
As a developer, I should have a coherent visualization of out of range dates in the Comparative and Search tool's timeline

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#374]
Where: Compare and Search tools

**Visualization issue**
when there are incorrect dates (outside the range) the timeline still displays them in the Compare tool, but not in the Search tool.
Solution: choose one approach of the two, and make the visualization coherent. In any case, if there are wrong dates, this information show ideally be shown somewhere for transparency purposes.

How to reproduce: 
-In the search tool, select television collection, leave empty search term. Save query
-In the compare, use Compare for the saved query
observe the timeline chart in both.

*Compare timeline vizz with wrong dates*
![Screenshot 2019-05-01 at 14.32.07.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/25001e42-bfd7-48d6-a377-47a0c06ffb25)

*Same data/vizz in the Search tool*
![Screenshot 2019-05-01 at 14 44 56](https://user-images.githubusercontent.com/8133228/57017493-bc45fc80-6c1f-11e9-9eed-3cd0097b2926.png)

Issue related to: https://github.com/beeldengeluid/labo-components/issues/378

**Comment by jblom** [comment]
@lilimelgar nice find. Put it on the backlog

**Comment by avlisodraude** [comment]
**@jblom @lilimelgar **
Issue for labo-components project done in branch:
issue/#374-clean-data-returned-from-query

Pull request:
https://github.com/beeldengeluid/labo-components/pull/395

### Issue 
The comparison recipe wasn't filtering weird data (dates) as it happens in the Single Search Tool.

### What's been done?
Since the filter function for the graphs in Single Search Tool was what was needed to filter data in the Comparison tool I just move the 'filterWeirdDates' to an utility component and run the same function for the data before being rendered as graphs.
Now the data for those graphs gets filtered in the same way by using the getMinimunYear defined in the collectionConfigs.

### Screenshot
![Screenshot 2019-05-14 at 15.10.26.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/0c0c832a-3e2e-4a89-ba9d-53c9f6bdc741)

**Comment by jblom** [comment]
@avlisodraude just inspected the code, which is an improvement. It looks fine I guess. Merged it already. Will need to be properly tested

**Comment by lilimelgar** [comment]
Tested in test version, all OK

**Comment by jblom** [comment]
@lilimelgar check!
