### ISSUE TITLE
As a developer, I need to do a small fix to the chart legend/title when the user selects the end date only

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#376]
Where: Search tool.
Issue: If you leave Start date empty and choose an End date, then the text underneath the graph is incorrect, e.g. “Selected date range: everything before till 02-04-2019 (using: bg:publications.bg:publication.bg:sortdate)” 
The word "before till" should not be there in this case, only "till".

![Screenshot 2019-05-01 at 16 21 46](https://user-images.githubusercontent.com/8133228/57021693-40eb4780-6c2d-11e9-97ed-da00cb3956c2.png)

**Comment by avlisodraude** [comment]
@jblom @lilimelgar 
Issue for labo-components project done in branch :
issue/#376-modify-chart-legend-dateRange

Pull request created: https://github.com/beeldengeluid/labo-components/pull/394
### What's been done?
The text has been modified (simplified I hope)
for all the cases which are:
- No dates selected => No legend to show
- Only end date selected => 'Everything until DateSelected' (screenshot 1)
- Only start date selected => 'Everything since DateSelected' (screenshot 2)
- Both dates selected => 'Everything from StartDate until EndDate' (screenshot 3)

#### NOTES:  
- Field name used is appended to the legend as before. 
- The 'for' has been changed to 'since' but SINCE I am not an expert in the english language that can be modified if needed :-) 

### Screenshots
Screenshot 1
![Screenshot 2019-05-14 at 11.54.33.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/5e493fbc-a5c3-4300-baed-a8aaf20d8fa5)

Screenshot 2
![Screenshot 2019-05-14 at 12.01.49.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/d2b558fb-009a-449d-83d0-8cfee31847f0)

Screenshot 3
![Screenshot 2019-05-14 at 12.06.57.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/d79a1f59-d036-4617-a87f-3cc90dec4021)

**Comment by jblom** [comment]
@avlisodraude I merged this one. Looks ok. Once I deployed this @lilimelgar could test this on the test server
