### ISSUE TITLE
As a user, I only want the search results to include text about the matches with search terms if I have entered search terms

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/labo-components#404]
At present, if you select a new collection, then when the list of search results appears, each result contains the text "No matches in the archival metadata, matching terms found in the automatic enrichments".  This text is not appropriate, as no search terms have been entered that could be matched on.  The same applies for if you search with only facets, the text should not appear.

**Comment by avlisodraude** [comment]
**@jblom** 

Issue for labo-components project done in branch:
_issue/#404-remove-matches-msn-when-no-searchterm_

Pull request
_https://github.com/beeldengeluid/labo-components/pull/410_
### What's been done?
#### Functionality wise
The message regarding the number of matches is only displayed if a 'search term' is present in the query.

Since there are both code refactoring and actual functionality changes introduced I will go a bit into details. The changes not commented here but in the [pull request](https://github.com/beeldengeluid/labo-components/pull/410) are merely code refactoring.

#### Files affected

**CollectionConfig**
added searchTerm function parameter
`getResultSnippetData(rawResult, numHighlights, searchTerm = null)`

//don't call method if there is no search term in the query
`snippet['highlightMsg'] = searchTerm ? this.getMatchingTermsMsg(numHighlights, true) : null;`

#### SearchHit
In render()
// add param searchTerm to method
`const snippet = this.props.data.collectionConfig.getResultSnippetData(
			this.props.data.formattedData,
			this.props.data.numHighlights,
            this.props.data.searchTerm
		);`

#### SearchSnippet
// check if there is a message before replacing anything
`fixMsg = s => (s ? s.replace(new RegExp(/\|$/,"g"), "") : null);`


#### KBNewspaperAggrConfig (file not under version control)
// add searchTerm param to method in 
`getResultSnippetData(result, numHighlights, searchTerm = null) {
	    const snippet = super.getResultSnippetData(result, numHighlights, searchTerm);
	    snippet['playable']= false;
	    return snippet;`

**Comment by jwassenaarbg** [comment]
Looks good, works as expected

**Comment by jblom** [comment]
@avlisodraude @jwassenaarbg works good indeed, closing

**Comment by jblom** [comment]
@lilimelgar you can test this one on test
